image: "ubuntu:bionic"

stages:
  - build_library
  - build_tests
  - test
  - publish

before_script:
  - apt-get update
  - apt-get -y install build-essential
  - version=3.11
  - build=4
  - mkdir temp
  - cd temp
  - apt-get -y install wget
  - wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz
  - tar -xzvf cmake-$version.$build.tar.gz
  - cd cmake-$version.$build/
  - ./bootstrap
  - make -j$(nproc)
  - make install
  - cd ../..
  - rm -r temp

building:
  stage: build_library
  script:
    - mkdir build && cd build
    - cmake ..
    - make fnsim
    - cd ..
  artifacts:
    paths:
      - build/*

building_node_test:
  stage: build_tests
  script:
  - cd build
  - make test_node
  - cd ..
  artifacts:
    paths:
      - build/*
  dependencies:
    - building

building_link_test:
  stage: build_tests
  script:
  - cd build
  - make test_link
  - cd ..
  artifacts:
    paths:
      - build/*
  dependencies:
    - building

building_network_test:
  stage: build_tests
  script:
  - cd build
  - make test_network
  - cd ..
  artifacts:
    paths:
      - build/*
  dependencies:
    - building

testing_node:
  stage: test
  script:
  - cd build
  - ./test_node
  - cd ..
  dependencies:
    - building_node_test

testing_link:
  stage: test
  script:
  - cd build
  - ./test_link
  - cd ..
  dependencies:
    - building_link_test

testing_network:
  stage: test
  script:
  - cd build
  - ./test_network
  - cd ..
  dependencies:
    - building_network_test
  
pages:
  stage: publish
  script:
  - apt-get -y install graphviz
  - apt-get -y install doxygen
  - doxygen Doxyfile
  - mv documentation/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
