image: "daniloborquez/ubuntu:dborquez-fnsim"

stages:
  - build_library
  - build_tests
  - test
  - publish

building:
  stage: build_library
  script:
    - mkdir build && cd build
    - cmake ..
    - make fnsim
    - cd ..
  artifacts:
    paths:
      - build/*

building_node_test:
  stage: build_tests
  script:
  - cd build
  - make test_node
  - cd ..
  artifacts:
    paths:
      - build/*
  dependencies:
    - building

building_link_test:
  stage: build_tests
  script:
  - cd build
  - make test_link
  - cd ..
  artifacts:
    paths:
      - build/*
  dependencies:
    - building

building_network_test:
  stage: build_tests
  script:
  - cd build
  - make test_network
  - cd ..
  artifacts:
    paths:
      - build/*
  dependencies:
    - building

testing_node:
  stage: test
  script:
  - cd build
  - ./test_node
  - ./test_node -r junit > report_node.xml
  - cd ..
  dependencies:
    - building_node_test
  artifacts:
    when: always
    paths:
      - report_node.xml
    reports:
      junit: report_node.xml

testing_link:
  stage: test
  script:
  - cd build
  - ./test_link
  - ./test_link -r junit > report_link.xml
  - cd ..
  dependencies:
    - building_link_test
  artifacts:
    when: always
    paths:
      - report_link.xml
    reports:
      junit: report_link.xml

testing_network:
  stage: test
  script:
  - cd build
  - ./test_network
  - ./test_network -r junit > report_network.xml
  - cd ..
  dependencies:
    - building_network_test
  artifacts:
    when: always
    paths:
      - report_network.xml
    reports:
      junit: report_network.xml
  
pages:
  stage: publish
  script:
  - doxygen Doxyfile
  - mv documentation/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
