image: "daniloborquez/ubuntu:dborquez-fnsim"

stages:
  - build_library
  - build_tests
  - test
  - deploy

building:
  stage: build_library
  script:
    - mkdir build && cd build
    - cmake ..
    - make fnsim
    - cd ..
  artifacts:
    paths:
      - build/*

building_node_test:
  stage: build_tests
  script:
  - cd build
  - make test_node
  - cd ..
  artifacts:
    paths:
      - build/*
  dependencies:
    - building

building_link_test:
  stage: build_tests
  script:
  - cd build
  - make test_link
  - cd ..
  artifacts:
    paths:
      - build/*
  dependencies:
    - building

building_network_test:
  stage: build_tests
  script:
  - cd build
  - make test_network
  - cd ..
  artifacts:
    paths:
      - build/*
  dependencies:
    - building

testing_node:
  allow_failure: true
  needs: ["building_node_test"]
  stage: test
  script:
  - cd build
  - g++ -o test_node -fprofile-arcs -ftest-coverage ../test/test_node.cpp ../src/node.cpp 
  - ./test_node -r junit > report_node.xml
  after_script:
  - cd build
  - gcovr  --filter '\.\./src/node.cpp'
  - gcovr  --filter '\.\./src/node.cpp' --xml-pretty > cov_node.xml 
  - cd ..
  dependencies:
    - building_node_test
  artifacts:
    when: always
    paths:
      - build/report_node.xml
      - build/cov_node.xml
      - build/test_node*
    reports:
      junit: build/report_node.xml
      cobertura: build/cov_node.xml

testing_link:
  allow_failure: true
  needs: ["building_link_test"]
  stage: test
  script:
  - cd build
  - g++ -o test_link -fprofile-arcs -ftest-coverage ../test/test_link.cpp ../src/link.cpp 
  - ./test_link -r junit > report_link.xml
  after_script:
  - cd build
  - gcovr  --filter '\.\./src/link.cpp'
  - gcovr  --filter '\.\./src/link.cpp' --xml-pretty > cov_link.xml 
  - cd ..
  dependencies:
    - building_link_test
  artifacts:
    when: always
    paths:
      - build/report_link.xml
      - build/cov_link.xml
      - build/test_link*
    reports:
      junit: build/report_link.xml
      cobertura: build/cov_link.xml

testing_network:
  allow_failure: true
  needs: ["building_network_test"]
  stage: test
  script:
  - cd build
  - g++ -o test_network -fprofile-arcs -ftest-coverage ../test/test_network.cpp ../src/network.cpp ../src/node.cpp ../src/link.cpp
  - ./test_network -r junit > report_network.xml
  after_script:
  - cd build
  - gcovr --filter '\.\./src/network.cpp'
  - gcovr --filter '\.\./src/network.cpp' --xml-pretty > cov_network.xml 
  - cd ..
  dependencies:
    - building_network_test
  artifacts:
    when: always
    paths:
      - build/report_network.xml
      - build/cov_network.xml
      - build/test_network*
    reports:
      junit: build/report_network.xml
      cobertura: build/cov_network.xml
  
pages:
  stage: deploy
  script:
  - doxygen Doxyfile
  - mv documentation/html/ public/
  - cd build
  - lcov --capture --initial  --directory . --output-file base.info
  - g++ -o test_node -fprofile-arcs -ftest-coverage ../test/test_node.cpp ../src/node.cpp 
  - ./test_node
  - if [[ $? != 0 ]]; then echo "Test failed" fi
  - lcov  --capture  --directory . --output-file test_node.info
  - g++ -o test_link -fprofile-arcs -ftest-coverage ../test/test_link.cpp ../src/link.cpp 
  - ./test_link
  - if [[ $? != 0 ]]; then echo "Test failed" fi
  - lcov  --capture  --directory . --output-file test_link.info
  - g++ -o test_network -fprofile-arcs -ftest-coverage ../test/test_network.cpp ../src/network.cpp ../src/node.cpp ../src/link.cpp
  - ./test_network
  - if [[ $? != 0 ]]; then echo "Test failed" fi
  - lcov  --capture  --directory . --output-file test_network.info
  - lcov --add-tracefile test_node.info --add-tracefile test_link.info --add-tracefile test_network.info --output-file total.info
  - lcov --remove total.info '*/c++/*' '*test*' '*.hpp' -o final.info
  - mkdir ../public/coverage-details
  - genhtml --prefix .  --ignore-errors source final.info --legend --title "commit SHA1" --output-directory=../public/coverage-details
  - cd ..
  artifacts:
    paths:
    - public
  only:
  - master
