image: "ubuntu:bionic"

before_script:
  - apt-get update
  - apt-get -y install build-essential
  - version=3.11
  - build=4
  - mkdir temp
  - cd temp
  - apt-get -y install wget
  - wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz
  - tar -xzvf cmake-$version.$build.tar.gz
  - cd cmake-$version.$build/
  - ./bootstrap
  - make -j$(nproc)
  - make install
  - cd ../..
  - rm -r temp
  - apt-get -y install doxygen

building:
  script:
    - mkdir build && cd build
    - cmake ..
    - make
    - cd ..

test:
  script:
  - doxygen Doxyfile
  except:
  - master
  
pages:
  script:
  - doxygen Doxyfile
  - mv documentation/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
